<div id="rapyd_div">
    <h1 id="rapyd_test_mode" style="display: none; color: red;margin-bottom: 15px;">Please contact store support. Our checkout is still in test mode and we can’t complete your transaction.</h1>
    <img id="rapyd_loader_div" style="width:50px;height:50px;display:block; margin:0 auto;position: relative;top: 200px;z-index: 2;" src="https://cdn.rapyd.net/plugins/icons/loader.gif"></img>
<div id="rapyd-checkout"></div>
</div>

<script>
    var rapyd_data = '<?php echo $this->getAction()?>';
    rapyd_data = JSON.parse(rapyd_data);
</script>

<script src="<?php  if (!empty($block)) {
    echo $block->rapyd_get_toolkit_url();
} ?>"></script>

<script src="<?php  if (!empty($block)) {
    echo $block->getViewFileUrl('Rapyd_Rapydmagento2::js/rapyd-public.js');
} ?>"></script>


